# HackRF Spectrum Monitor Configuration

# Spectrum configuration
spectrum:
  freq_min_mhz: 2400.0      # Start frequency in MHz
  freq_max_mhz: 2492.5     # End frequency in MHz (matches baseline coverage)
  bin_width: 250000      # FFT bin width in Hz (1 MHz for good performance)

# HackRF settings
hackrf:
  lna_gain: 16            # LNA gain (0-40dB, 8dB steps)
  vga_gain: 20            # VGA gain (0-62dB, 2dB steps)
  amp_enable: false       # RF amplifier enable
  antenna_enable: false   # Antenna port power enable
  one_shot: false         # Single sweep mode
  serial_number: ""       # Specific device serial (empty = auto)
  dc_spike_removal: true  # Remove DC spike from spectrum data
  dc_spike_width: 3       # Number of bins around DC to remove (1-10)

# Monitoring settings
monitoring:
  threshold_buffer_db: 10.0  # Detection threshold above baseline (dB)
  update_rate_hz: 10.0       # Spectrum update rate
  min_detection_duration_s: 0.5  # Signal must persist this long to alert

# Storage settings
storage:
  baseline_file: "baselines.npz"  # Learned baseline storage file
  learning_history: 1000          # Number of spectra to average in learning mode
  data_directory: "."             # Directory for data files

# Display settings
display:
  show_frequency_mhz: true        # Show frequencies in MHz vs Hz
  precision_digits: 1             # Decimal places for frequency display
  power_precision: 1              # Decimal places for power display
  alert_beep: false               # Audio alert on detection (requires system beep)
  
# Performance settings
performance:
  max_display_points: 2000        # Limit display points for performance
  processing_threads: 1           # Number of processing threads (1 = single threaded) 